### PR TITLE
Add dynamic user agent to http.ts

### PR DESCRIPTION
**Pull request by justinemmanuelmercado**

### CODE REVIEW

**Comment by moltar** [comment]
I've ran into an issue today on the advertising module and realized that my approach was not good.

You can see my changes here, and read the commit message for the explanation.

https://github.com/ScaleLeap/amazon-advertising-api-sdk/commit/8b01953541b88ff64756a4ca1c270cefffdf9997

Please copy this approach to MWS also.

Can do here or start a new PR - up to you.

Thanks.

**Comment by justinemmanuelmercado** [comment]
Copied exactly what you did in the advertising SDK, let me know if I missed something :+1:

**Comment by justinemmanuelmercado** [comment]
Oh uhm apparently I broke api-extractor here too 😅 but lint and unit tests passed

**Comment by moltar** [comment]
> Oh uhm apparently I broke api-extractor here too 😅 but lint and unit tests passed

Can we get that fixed>

**Comment by justinemmanuelmercado** [comment]
> Can we get that fixed?

You're right, I should've looked into it some more. I was thinking you knew the solution and that it would've been faster if you had a look. I'll look into it and the other issue some more before requesting a review

**Comment by justinemmanuelmercado** [comment]
This is good for review. my previous issue was I didn't copy the changes made to `tsconfig.json` and `tsconfig.build.json`. The error `api-extractor` threw sort of gave me an idea what the problem was, but I honestly did not know how to resolve it because I thought there wasn't any ts config files in the repo and that it was all inherited from `@scaleleap/config`, but I was just an idiot that did not realize you can hide files using `.vscode/settings.json` 🤣

**Comment by moltar** [comment]
> but I was just an idiot that did not realize you can hide files using .vscode/settings.json

Oops, sorry, my bad :D

**Pull request merged**
