### PR TITLE
Allow ASINs to be strings or numbers

### PR DESCRIPTION
**Pull request by mvd7793**
I hit this error on an item that had an ASIN that was just a number. :)

### CODE REVIEW

**Comment by ericblade** [comment]
Hi there!  FWIW, I'm not working on this project, keep an eye on it because it's related to things I do work on, but you should probably be passing it a string anyway, even if it is an all numeric ASIN -- pure numeric ASINs are almost always a 10-digit ISBN book code, and many start with "0", which is not preserved if you pass a number.

**Comment by mvd7793** [comment]
Thanks @ericblade! From what I understand, this code does validation on the Amazon response that occurs before any other code runs, though it's an excellent point that it might be nice to keep it as strings if we can change the Codec to do transformation instead of validation. I'm not as familiar with the Codec system -- I'll let the maintainers chime in.

**Comment by moltar** [comment]
@ericblade is right and all identifiers are strings. Sometimes you can get an ISBN, which is numeric.

I am guessing the XML parsing library is trying to be smart and if it sees all digits, then it simply assumes it is a number. Need to look into that and possibly disable that behavior.

Or simply just `.toString()` everything to force it to be a string.

@justinemmanuelmercado please look into that when you have time.

We probably don't need this PR, but the issue still remains.

**Comment by mvd7793** [comment]
FWIW the error I was encountering was on ASIN [1452162794](https://www.amazon.com/dp/1452162794), which is a board game with a numerical ASIN, not a book. Some other fix is totally okay too -- keeping everything as strings seems nice, I just wasn't sure how to override the functionality in the parsing checker. :D

**Comment by justinemmanuelmercado** [comment]
Hey @mvd7793, thanks for bringing this up! Sorry I couldn't get to it sooner. 

I address this in https://github.com/ScaleLeap/amazon-mws-api-sdk/pull/211 with a small explanation and after I get that reviewed, that should fix the issue you were having.

Feel free to let us know if issues like this arise again. It's been a big help. Thanks 👍

**Pull request closed without merging**
