### PR TITLE
feature: fulfillment-inbound-shipment

### PR DESCRIPTION
**Pull request by justinemmanuelmercado**

### CODE REVIEW

**Comment by justinemmanuelmercado** [comment]
Hey @moltar, not sure if this is important. https://github.com/ScaleLeap/amazon-mws-api-sdk/runs/872982551 
`npm run api-extractor` throws

```Error: Internal Error: _notifyReferencedAstEntity() called after analysis is already complete
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.```

Running locally has the same behavior

**Comment by justinemmanuelmercado** [comment]
Hey @moltar, this is ready for review. I'm still accomplishing the docs for this but the FIS API is finished. I'll merge it to master after finalizing the docs and getting after your review.

**Comment by moltar** [comment]
> npm run api-extractor

Interesting ... runs fine for me :/

```
❯ npm run api-extractor

> @scaleleap/amazon-mws-api-sdk@1.4.0 api-extractor /foo/@scaleleap/amazon-mws-api-sdk
> api-extractor run --local --verbose


api-extractor 7.8.1  - https://api-extractor.com/

Using configuration from /foo/@scaleleap/amazon-mws-api-sdk/api-extractor.json

Writing: /foo/@scaleleap/amazon-mws-api-sdk/temp/amazon-mws-api-sdk.api.json
Writing package typings: /foo/@scaleleap/amazon-mws-api-sdk/dist/amazon-mws-api-sdk.d.ts
Warning: dist/amazon-mws-api-sdk.d.ts:249:65 - (TS2749) 'MWSApiError' refers to a value, but is being used as a type here.
Warning: dist/amazon-mws-api-sdk.d.ts:288:24 - (TS2307) Cannot find module '../../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:311:24 - (TS2307) Cannot find module '../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:1383:23 - (TS2307) Cannot find module '../../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:1413:31 - (TS2307) Cannot find module '../../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:1449:31 - (TS2307) Cannot find module '../../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:1479:23 - (TS2307) Cannot find module '../../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:2609:31 - (TS2307) Cannot find module '../../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:3747:31 - (TS2307) Cannot find module '../../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:5320:24 - (TS2307) Cannot find module '../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:5391:24 - (TS2307) Cannot find module '../../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:5604:24 - (TS2307) Cannot find module '../parsing'.
Warning: dist/amazon-mws-api-sdk.d.ts:5650:24 - (TS2307) Cannot find module '../parsing'.
Warning: lib/error.d.ts:96:22 - (ae-forgotten-export) The symbol "MWSApiError" needs to be exported by the entry point index.d.ts
Warning: lib/http.d.ts:59:22 - (ae-forgotten-export) The symbol "Parameters" needs to be exported by the entry point index.d.ts
Warning: lib/http.d.ts:59:22 - (ae-forgotten-export) The symbol "CleanParameters" needs to be exported by the entry point index.d.ts
Warning: lib/http.d.ts:63:5 - (ae-forgotten-export) The symbol "Request" needs to be exported by the entry point index.d.ts
Warning: lib/http.d.ts:63:5 - (ae-forgotten-export) The symbol "RequestResponse" needs to be exported by the entry point index.d.ts
Warning: lib/http.d.ts:64:5 - (ae-forgotten-export) The symbol "HttpMethod" needs to be exported by the entry point index.d.ts
Warning: lib/http.d.ts:64:5 - (ae-forgotten-export) The symbol "ResourceInfo" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:31:1 - (ae-forgotten-export) The symbol "ListFinancialEventGroups" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:67:17 - (ae-forgotten-export) The symbol "ProcessingStatusEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:1314:1 - (ae-forgotten-export) The symbol "ListFinancialEvents" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:2454:25 - (ae-forgotten-export) The symbol "ChargeTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:2496:25 - (ae-forgotten-export) The symbol "DirectPaymentTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:2516:29 - (ae-forgotten-export) The symbol "TaxCollectionModelEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3234:21 - (ae-forgotten-export) The symbol "FulfillmentChannelEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3238:21 - (ae-forgotten-export) The symbol "ProviderTransactionTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3248:21 - (ae-forgotten-export) The symbol "RetrochargeEventTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3273:21 - (ae-forgotten-export) The symbol "RentalEventTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3313:21 - (ae-forgotten-export) The symbol "transactionTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3344:21 - (ae-forgotten-export) The symbol "DebtRecoveryTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3379:21 - (ae-forgotten-export) The symbol "SourceBusinessEventTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3382:21 - (ae-forgotten-export) The symbol "AdjustmentTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/codec.d.ts:3549:21 - (ae-forgotten-export) The symbol "NetworkComminglingTransactionTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/finances.d.ts:10:1 - (ae-forgotten-export) The symbol "RequireOnlyOne" needs to be exported by the entry point index.d.ts
Warning: lib/sections/finances/finances.d.ts:20:5 - (ae-forgotten-export) The symbol "NextToken" needs to be exported by the entry point index.d.ts
Warning: lib/sections/fulfillment-inventory.d.ts:98:1 - (ae-forgotten-export) The symbol "InventorySupplyList" needs to be exported by the entry point index.d.ts
Warning: lib/sections/fulfillment-inventory.d.ts:99:1 - (ae-forgotten-export) The symbol "InventorySupplyListByNextToken" needs to be exported by the entry point index.d.ts
Warning: lib/sections/orders.d.ts:300:1 - (ae-forgotten-export) The symbol "Order" needs to be exported by the entry point index.d.ts
Warning: lib/sections/orders.d.ts:301:1 - (ae-forgotten-export) The symbol "ListOrders" needs to be exported by the entry point index.d.ts
Warning: lib/sections/orders.d.ts:302:1 - (ae-forgotten-export) The symbol "ListOrderItems" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:34:13 - (ae-forgotten-export) The symbol "IdTypeEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:64:9 - (ae-forgotten-export) The symbol "StatusEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:499:17 - (ae-forgotten-export) The symbol "ItemConditionEnum" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:631:1 - (ae-forgotten-export) The symbol "ListMatchingProducts" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:637:1 - (ae-forgotten-export) The symbol "GetLowestPricedOffersForSKU" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:638:1 - (ae-forgotten-export) The symbol "GetLowestPricedOffersForASIN" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:639:1 - (ae-forgotten-export) The symbol "GetMyPriceForSKUResult" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:640:1 - (ae-forgotten-export) The symbol "GetMyPriceForASINResult" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:641:1 - (ae-forgotten-export) The symbol "GetProductCategoriesForSKU" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/codec.d.ts:642:1 - (ae-forgotten-export) The symbol "GetProductCategoriesForASIN" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/type.d.ts:22:5 - (ae-forgotten-export) The symbol "MoneyType" needs to be exported by the entry point index.d.ts
Warning: lib/sections/products/type.d.ts:42:5 - (ae-forgotten-export) The symbol "PriceToEstimateFees" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:10:1 - (ae-forgotten-export) The symbol "ReportType" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:30:1 - (ae-forgotten-export) The symbol "ReportRequestInfo" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:85:1 - (ae-forgotten-export) The symbol "GetReportRequestListResult" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:98:1 - (ae-forgotten-export) The symbol "GetReportRequestCount" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:132:1 - (ae-forgotten-export) The symbol "CancelReportRequests" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:163:1 - (ae-forgotten-export) The symbol "GetReportListResult" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:174:1 - (ae-forgotten-export) The symbol "GetReportCount" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:192:1 - (ae-forgotten-export) The symbol "ManageReportSchedule" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:209:1 - (ae-forgotten-export) The symbol "GetReportScheduleList" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:216:1 - (ae-forgotten-export) The symbol "GetReportScheduleCount" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:239:1 - (ae-forgotten-export) The symbol "UpdateReportAcknowledgements" needs to be exported by the entry point index.d.ts
Warning: lib/sections/reports.d.ts:254:5 - (ae-forgotten-export) The symbol "Report" needs to be exported by the entry point index.d.ts
Warning: lib/sections/sellers.d.ts:24:5 - (ae-forgotten-export) The symbol "MarketplaceParticipations" needs to be exported by the entry point index.d.ts
Warning: lib/sections/subscriptions.d.ts:33:1 - (ae-forgotten-export) The symbol "MarketplaceIdAndDestinationOnlyParameters" needs to be exported by the entry point index.d.ts
Warning: lib/sections/subscriptions.d.ts:82:1 - (ae-forgotten-export) The symbol "ListRegisteredDestinations" needs to be exported by the entry point index.d.ts
Warning: lib/sections/subscriptions.d.ts:83:1 - (ae-forgotten-export) The symbol "GetSubscription" needs to be exported by the entry point index.d.ts

API Extractor completed successfully
```

**Comment by moltar** [comment]
Ah okay, never mind! I ran it on an older build.

**Comment by moltar** [comment]
Have you looked at https://github.com/microsoft/rushstack/issues/1108?

Seems to be a related error.

**Comment by justinemmanuelmercado** [comment]
> Have you looked at [microsoft/rushstack#1108](https://github.com/microsoft/rushstack/issues/1108)?

This might be it. I thought it was an `api-extractor` issue. I'll look into it. Thanks for the heads up

**Comment by moltar** [comment]
Well it does sound like extractor issue. I think they said it's a confirmed bug. But I think there's an explanation and possible workaround. Didn't check too much.

**Pull request merged**
