### PR TITLE
feat: products api

### PR DESCRIPTION
**Pull request by justinemmanuelmercado**

### CODE REVIEW

**Comment by moltar** [comment]
# [Codecov](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45?src=pr&el=h1) Report
> Merging [#45](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45?src=pr&el=desc) into [master](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/commit/93479071112dd7beba069ca13e81eee93f8e4257&el=desc) will **increase** coverage by `0.02%`.
> The diff coverage is `100.00%`.

[Impacted file tree graph](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master      #45      +/-   ##
==========================================
+ Coverage   99.76%   99.79%   +0.02%     
==========================================
  Files          13       14       +1     
  Lines         426      483      +57     
  Branches       41       46       +5     
==========================================
+ Hits          425      482      +57     
  Partials        1        1              
```


| [Impacted Files](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/mws.ts](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45/diff?src=pr&el=tree#diff-c3JjL213cy50cw==) | `100.00% <100.00%> (ø)` | |
| [src/sections/products.ts](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45/diff?src=pr&el=tree#diff-c3JjL3NlY3Rpb25zL3Byb2R1Y3RzLnRz) | `100.00% <100.00%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45?src=pr&el=footer). Last update [9347907...7dbdad3](https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/pull/45?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by justinemmanuelmercado** [comment]
Roadblocked by issue #46. Will be switching gears until #46 gets merged to master

**Comment by justinemmanuelmercado** [comment]
Just adding some details as to why I updated some enums to strings

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/2a4768e1f10dda1bd258451c83db7c53ef782d2c/src/sections/products.ts#L107

Because Amazon's own sample responses don't follow the enumerated types in their docs

**Comment by justinemmanuelmercado** [comment]
NOTES TO SELF REGARDING `GetMatchingProduct` and `GetMatchingProductForId`:

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/011bb67827a72207cde41dbc1ffa80242d988790/src/sections/products.ts#L172-L176

The possible types for `GetMatchingProductForIdResult` is structured unusually but it makes sense in this context. The array starts higher in the hierarchy than usual. Also it's possible that instead of an array an object is in its place. This is because instead of just a single child in the XML file under the <GetMatchingProductForIdResponse> parent tag it's possible that there is more than one child named <GetMatchingProductForIdResult>

It tripped me up at first and due to the similarity in wording of the description from Amazon's docs of this API and the API for `GetMatchingProduct` I suspect that this is the correct structure for that API as well though Amazon's example in the docs for the latter did not explicitly show it.

**Comment by moltar** [comment]
> Also it's possible that instead of an array an object is in its place.

@justinemmanuelmercado I think this is applicable to every response. Because of the nature of XML, we can never be sure if it is just one item or an array of items.

That is why there is a helper function `ensureArray`.

See usage:

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/494518bd65c89ad10ad109e0c76757777db48f05/src/sections/orders.ts#L204

**Comment by justinemmanuelmercado** [comment]
> @justinemmanuelmercado I think this is applicable to every response. Because of the nature of XML, we can never be sure if it is just one item or an array of items.

@moltar Yeah I was using `ensureArray` earlier but for some reason it didn't work as I expected. But it looks like I was just using it in the wrong place. Fixed it now, thanks!

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/d18b8bd00ac62db983ff8c37ddd8dba8eec76d79/src/sections/products.ts#L201-L204

**Comment by justinemmanuelmercado** [comment]
Besides integration tests, this looks like it's okay for merging to master. Let me know if there's anything to improve

**Pull request merged**
