### PR TITLE
refactor: create products codec

### PR DESCRIPTION
**Pull request by justinemmanuelmercado**

### CODE REVIEW

**Comment by justinemmanuelmercado** [comment]
I was hesitant to create the codec for `Product` when I was working on the products api previously because the XSDs were sort of intimidating. Fortunately Amazon defines the product in their C# library. That's where I'm basing the `Product` codec now, instead of relying on the Amazon docs examples

**Comment by justinemmanuelmercado** [comment]
This was just pretty quick. After looking over the docs and the types from the C# library I figured out that `Product` has 7 sub-attributes, and each different response's `Product` contains a different combination of those 7 sub attributes. i.e. in `GetMatchingProduct` the description under it's `Product` says `"Contains four of the sub-elements of the Product element from ProductsAPI_Response.xsd. These sub-elements are: Identifiers, AttributeSets, Relationships, and SalesRankings. "`. 

I based most of the codec definitions on how they're defined in the C# library, I didn't change the unit tests so it looks like the documentations sample responses agree with the structure defined in the C# library. There are attributes defined as `"abstract"` in the C# SDK though and I'm guessing those are the complicated "anything goes" object where almost anything can be defined under them.

**Comment by moltar** [comment]
Great, yeah C# can be a really good source of truth. I've looked in that code base countless times trying to figure out responses sometimes 😁

**Comment by moltar** [comment]
@justinemmanuelmercado is there anything blocking merging this?

**Comment by justinemmanuelmercado** [comment]
For some reason I thought I already merged this 😅

**Pull request merged**
