### PR TITLE
refactor: #148 validate XML and handle HTML entities

### PR DESCRIPTION
**Pull request by justinemmanuelmercado**

### CODE REVIEW

**Comment by justinemmanuelmercado** [comment]
Hey @moltar, wanted to get your opinion on this. So first I set an option on FXP to validate the XML before passing it onto `purify-ts` to be parsed and it throws a parsing error with the error message from FXP if it receives an invalid XML string. You can see it here in this commit https://github.com/ScaleLeap/amazon-mws-api-sdk/pull/149/commits/bb5a5a59c72c719234d3bb1782bd3763057fcccf.

Unfortunately that made the coverage worse. Since I was catching all the errors before it gets parsed that meant this portion of all the methods don't get covered in the unit tests https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/e1a033d4a555af3233da7341cf9b4be3bd785a93/src/sections/sellers.ts#L85-L88

My thinking is that makes sense since I'm catching all XML errors beforehand and previously we were just testing with a blank string to trigger the parsing error, which is rightfully so being caught by FXP's validation. 

I think that it's worth it to enable FXP's validation and catch parsing errors before it gets decoded by `purify-ts` and that I should just create an alternative unit test that makes it so that it's a valid XML but it gets decoded as invalid by `purify-ts` for coverage.

I can also just leave it as is since I think `purify-ts` could catch invalid XML anyway

**Comment by moltar** [comment]
> Unfortunately that made the coverage worse.

What do you mean by that? I am not seeing anything worse on this PR.

---

Other than that, I think it is a good idea to validate XML.

**Comment by justinemmanuelmercado** [comment]
Sorry it wasn't clear, but I'm talking about this

https://codecov.io/gh/ScaleLeap/amazon-mws-api-sdk/src/bb5a5a59c72c719234d3bb1782bd3763057fcccf/src/sections/fulfillment-inbound-shipment/fulfillment-inbound-shipment.ts# 

Screen Shot 2020-07-23 at 9 45 16 PM

From what I understand is the coverage decreased because FXP will throw the error beforehand but before the change the invalid XML tests passed this line of code

```
      Left: (error) => {
        throw new ParsingError(error)
      },
```

but now it gets throw before that

**Comment by justinemmanuelmercado** [comment]
The solution I'm thinking of is just adding another unit test to have valid XML but invalid structure to let `purify` throw something. But I wanted your opinion if you think that it's necessary

**Comment by justinemmanuelmercado** [comment]
So I pushed a few more changes which fix the issues I found whilst testing `xml2js`

Validation is handled by FXP and throws an error for invalid XMLs, this messes up the code coverage though but I think it's worth it. I'll make another PR to handle adding a unit test to fix the unit test code coverage

Added [`html-entities`](https://www.npmjs.com/package/html-entities) to handle decoding of XML entities (i.e. `&quot` gets converted to `"` and `&amp` to `&`). 

Let me know what you think

**Pull request merged**
