### PR TITLE
feature: documentation

### PR DESCRIPTION
**Pull request by justinemmanuelmercado**

### CODE REVIEW

**Comment by justinemmanuelmercado** [comment]
Hey @moltar, finished the docs for all the params of all the requests, check it out here https://github.com/ScaleLeap/amazon-mws-api-sdk/tree/feature/25-documentation/docs

**Comment by justinemmanuelmercado** [comment]
@moltar Also in this PR I included some fixes to types/codecs whilst I was combing through the Amazon docs. They're the 'fix' commits. I'm off for the weekend but feel free to leave comments and suggestions.

**Comment by justinemmanuelmercado** [comment]
Thanks! I'll make a checklist for the changes

- [ ] Minimal code examples
- [ ] "Let's also add links to our examples/, where we have examples. Especially when it says "See examples for sample usage" -- should definitely link to a specific example."
- [ ] "There is no mention of the meta object. I think we should focus on that early on, because it is somewhat unconventional to return a tuple in JS-land, so I think very early on, we need to explain why & how it works, and show examples of meta usage too (console.log type example, I think is enough)."
- [ ] "You still didn't add yourself to "Authors or Acknowledgments" section! And don't forget the package.json authors section too! 😁"

**Comment by moltar** [comment]
There are still cases of italic. E.g. see `getFeedSubmissionList` section.

Also, I meant to code format ALL of the example values. I think it'll look nicer and more readable. What do you think?

**Comment by justinemmanuelmercado** [comment]
Ahh my bad, I thought I got them all. That sounds like a good idea actually, might do just that

**Comment by justinemmanuelmercado** [comment]
What about the code samples? Http client, request data, and next token sections? Do you have any comments about those? @moltar

**Comment by moltar** [comment]
I think any code should have code formatting. The only annoying part is that inside markdown tables don’t think it’s possible to have multi line code blocks. So we cab only use single ticks.

**Comment by justinemmanuelmercado** [comment]
Added single ticks around the code in tables and did some quick skims and fixed some issues I found. I think this should be good, based on your earlier suggestions. Let me know what you think and if you have anymore changes you had in mind. @moltar

**Pull request merged**
