### PR TITLE
Add suffix to error classes

### PR DESCRIPTION
**Pull request by justinemmanuelmercado**

### CODE REVIEW

**Comment by justinemmanuelmercado** [comment]
I tried something like this because my vscode's lint/ts was complaining
```typescript
export * as Errors from './error'
```
But `api-extractor` complained so I used something like the code below
```typescript
import * as error from './error'

export const Errors = error
```
But `api-extractor` still complained and then I read https://stackoverflow.com/a/59712387 so I put it back to `export * as Errors from './error'` but `api-extractor` complained, so I think api-extractor and my local vscode's linter is wrong since the typescript we use is <3.8

**Comment by justinemmanuelmercado** [comment]
Oh yeah so the prob is only with `api-extractor` now. I updated my local vscode ts version to 3.9 and it stopped complaining about `export * as Errors from './error'`. Not sure if I should ignore `api-extractor` though

**Comment by justinemmanuelmercado** [comment]
@moltar, not sure if you've seen this yet. Everything works with `lint` and unit tests but API extractor is not compiling due to this line

`export * as Errors from './error'` at `index.ts`

**Comment by moltar** [comment]
Have you tried:

```ts
import * as Errors from './error'

export { Errors }
```

?

**Comment by justinemmanuelmercado** [comment]
```typescript
import * as Errors from './error'

export { Errors }
```
This makes api-extractor throw `Error: "import * as ___ from ___;" is not supported yet for local files.`

Reverting to 
```typescript
export * as Errors from './error'
```
Threw an unknown "software error". I upgraded api-extractor to 3.9.7 and that changed the thrown error to `Unimplemented export declaration kind: * as Errors`.

I tried something in my latest commit, not sure if you think it's an okay workaround. Also had to revert `api-extractor` back to 3.8.1 because the previous issue with `Error: The expression contains an import() type, which is not yet supported by API Extractor:` still isn't resolved

**Comment by justinemmanuelmercado** [comment]
This feels weird but I'm not sure if there's any issue with an implementation like this 

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/42d3f6b56013331f32f87cd7f8553318e017e5f1/src/error.ts#L84-L128

Let me know what you think, also I think it's also possible to just export the `Errors` object and not export the individual error files but I don't think there's any issues with exporting both.

**Comment by moltar** [comment]
> This feels weird but I'm not sure if there's any issue with an implementation like this

This is fragile as someone will for sure forget to add a new class.

Let's just drop this feature for now. I.e. the grouping export. But leave the rename.

**Comment by justinemmanuelmercado** [comment]
> This is fragile as someone will for sure forget to add a new class.

Ahh I see, good point. Fixed, this is ready for review now

**Pull request merged**
